/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function JillsRoom(props) {
  const { nodes, materials } = useGLTF("/assets/va11cleaned.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Untitled.geometry}
        material={materials.Untitled_Material}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/va11cleaned.glb");